# Importing Libraries

In [63]:
#for preprocessing 
import numpy as np 
import pandas as pd 
from matplotlib import pyplot as plt
import seaborn as sns

#for prediction 
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,accuracy_score,recall_score, precision_score
from sklearn.model_selection import cross_val_score


import warnings
warnings.filterwarnings('ignore')

# Loading the data

In [27]:
data = pd.read_csv('Titanic-Dataset.csv')

data.head()


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [28]:
data.shape

(891, 12)

In [29]:
data.info()  

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
plt.hist()

# Data preprocessing  

In [30]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [31]:
##dropping columns than not affect on target 
data= data.drop(["Name","PassengerId","Ticket","Cabin"],axis=1, errors='ignore')
data.columns


Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='object')

In [32]:
##check missing values 

data.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [33]:
#handling missing values in Age ,Embarked and  Caibin

data['Age'].fillna(data['Age'].median(), inplace=True)
data['Embarked'].fillna('S', inplace=True)



In [34]:
data.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [35]:
data.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

# Model Creation 

In [36]:
data.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='object')

In [49]:
##lable encoding for "sex" 
le = LabelEncoder()
data["Sex"] = le.fit_transform(data["Sex"])

##Mapping for "Embarked"
data['Embarked'] = data['Embarked'].map({'S': 0 , 'C':1 , 'Q':2})

data.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         0
1         1       1    0  38.0      1      0  71.2833         1
2         1       3    0  26.0      0      0   7.9250         0
3         1       1    0  35.0      1      0  53.1000         0
4         0       3    1  35.0      0      0   8.0500         0

In [50]:
x = data[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare','Embarked']]
y = data[["Survived"]]

In [51]:
## devide data into train and test 
x_train , x_test , y_train ,y_test = train_test_split(x,y,test_size = 0.2, random_state = 42)

In [52]:
x_test.shape

(179, 7)

In [53]:
x_train.shape 

(712, 7)

In [54]:
model = LogisticRegression()
model.fit(x_train , y_train)

LogisticRegression()

# Model Evaluation

In [56]:
y_pred=model.predict(x_test)


In [57]:
y_pred 

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1], dtype=int64)

In [58]:

cm=confusion_matrix(y_test,y_pred)
print(cm)

[[89 16]
 [20 54]]


In [60]:
acc = accuracy_score(y_test , y_pred )
acc 

0.7988826815642458

In [61]:
recall = recall_score(y_test ,y_pred ) 
recall 

0.7297297297297297

In [62]:
precision = precision_score(y_test , y_pred)
precision 

0.7714285714285715

# Cross Validation 

In [64]:
cross_val = cross_val_score(model,x,y,cv=10,scoring = 'accuracy')


In [65]:
cross_val 

array([0.78888889, 0.79775281, 0.74157303, 0.83146067, 0.79775281,
       0.76404494, 0.78651685, 0.78651685, 0.82022472, 0.83146067])

In [66]:
# if std() less than 0.05, we say the model is working good ............................
print('Cross validation score',cross_val.std())


Cross validation score 0.02702347765082892


In [67]:
#Training Acc 

y_pred_train = model.predict(x_train)
accuracy_score(y_pred_train,y_train)

0.800561797752809